ims/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
	path("", include("main.urls")),
	path("", include("product.urls")),
	path("", include("store.urls")),
	path("", include("customer.urls")),
	path("", include("purchase.urls")),
	path("", include("account.urls")),

]

store/urls.py
from django.urls import path
from . import views

app_name = "store"

urlpatterns = [

	path("add-store/", views.AddStoreView, name="add_store"),
	path("all-store/", views.AllStoreView, name="all_store"),
	path("delete-store/<int:store_id>/", views.DeleteStoreView, name="delete_store"),
	path("edit-store/<int:store_id>/", views.EditStoreView, name="edit_store"),
	

]

store/models.py
from django.db import models
from product.models import Product
from django.utils import timezone

# Create your models here.
class Store(models.Model):
	name = models.CharField(max_length=150)
	products = models.ManyToManyField(Product, through="StoreProductConnector", through_fields=("store", "product"),)
	low_qty = models.IntegerField(blank=True, null=True)
	high_qty = models.IntegerField(blank=True, null=True)
	description = models.TextField(default="just a store")
	store_id  = models.CharField(max_length=150)
	pub_date = models.DateTimeField(default=timezone.now)
	
	
	def __str__(self):
		return self.name
	
	
	
class StoreProductConnector(models.Model):
	store = models.ForeignKey(Store, on_delete=models.CASCADE, default="")
	product = models.ForeignKey(Product, on_delete=models.CASCADE, default="")
	pub_date = models.DateTimeField(default=timezone.now)

store/views.py
from store.models import Store
from main.views import ray_randomiser
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy

# Create your views here.
def AddStoreView(request):
	if request.method == "POST":
		name = request.POST.get("name")
		low_qty = request.POST.get("low_qty")
		high_qty = request.POST.get("high_qty")
		description = request.POST.get("description")
		store_id = ray_randomiser()
		pub_date = timezone.now()
		
		if name == "":
			return HttpResponse("Please enter a Store name")
		else:
			store = Store.objects.create(name=name, low_qty=low_qty, high_qty=high_qty, description=description, store_id=store_id, pub_date=pub_date)
			store.save()
			return HttpResponseRedirect(reverse("store:all_store"))
		
	else:
		return render(request, 'store/add_store.html')
		
	
def AllStoreView(request):
	stores = Store.objects.order_by("-pub_date")

	context = {"stores": stores}
	return render(request, "store/all_store.html", context)
	
	
	
def DeleteStoreView(request, store_id):
	store = Store.objects.get(id=store_id)
	store.delete()
	#post.save()
		
	return HttpResponseRedirect(reverse("store:all_store"))
	
	
def EditStoreView(request, store_id):
	if request.method == "POST":
		name = request.POST.get("name")
		low_qty = request.POST.get("low_qty")
		high_qty = request.POST.get("high_qty")
		description = request.POST.get("description")
		
		store = Store.objects.filter(id=store_id)
		store.update(name=name, low_qty=low_qty, high_qty=high_qty, description=description)

	
		return HttpResponseRedirect(reverse("store:all_store"))
		
		
	else:
		store = get_object_or_404(Store, id=store_id)
		context = {"store": store}
		return render(request, 'store/edit_store.html', context)
	
	

store/templates/store/add_store.html
{% extends 'main/base.html' %}
  

{% block content %}
<style type="">
    .card{
    box-shadow: -1px 9px 40px -12px rgba(255,110,110,0.9);
    }
    .card-title{
        font-size: 25px;
        letter-spacing: 1px;
        font-family: Patua One;
        font-weight: 300;
        color: white !important;
        text-shadow: 6px 6px 6px #c9c6c6;
    }
    .card-title1{
        font-size: 25px;
        letter-spacing: 1px;
        font-family: Patua One;
        font-weight: 300;
        color: #357ab7 !important;
        text-shadow: 6px 6px 6px #c9c6c6;
    }


    .bttn{
        background-color: #357ab7;
    }
    .bttn:hover{
        background-color: teal;
        color: white;
        transition:  all 0.5s ease-in-out;
        transform: scale(1.05);
    }
    .card-body{
        background-color: #001f3f;
        color: white;
    }
    .filter{
        font-family: Rufina;
    }

</style>	

<div class="row">
                    <div class="col-md-10">
                        <div class="card">
                            <div class="card-header">
                                <strong class="card-title1">Setup Store</strong>
                            </div>
                            <div class="card-body">
                                <!-- Credit Card -->
                                <div id="pay-invoice">
                                    <div class="card-body">
                                        <div class="card-title">
                                            <h3 class="text-center">Create Store</h3>
                                        </div>
                                        <hr>
                                        <form novalidate="novalidate" method="post" enctype="multipart/form-data">
				{% csrf_token %}
                                            
                                            <div class="form-group">
                                                <label for="cc-payment" class="control-label mb-1">Store  Name</label>
                                                <input id="cc-payment" name="name" type="text" class="form-control" aria-required="true" aria-invalid="false">
                                            </div>
                                            <div class="row form-group">
				                                <div class="col col-md-3"><label for="select" class=" form-control-label">Product Threshold</label></div>
				                                <div class="col-12 col-md-9">
				                                    <select name="low_qty" id="select" class="form-control">
				                                       <option value="0">0 qty</option>
				                                        <option value="5">5 qty</option>
				                                        <option value="10">10 qty</option>
				                                        <option value="20">20 qty</option>
				                                        <option value="50">50 qty</option>
				                                         <option value="100">100 qty</option>
				                                    </select>
				                                </div>
				                            </div>
				                            <div class="row form-group">
				                                <div class="col col-md-3"><label for="select" class=" form-control-label">Highest Limit</label></div>
				                                <div class="col-12 col-md-9">
				                                    <select name="high_qty" id="select" class="form-control">
				                                       <option value="0">0 qty</option>
				                                        <option value="5">5 qty</option>
				                                        <option value="10">10 qty</option>
				                                        <option value="20">20 qty</option>
				                                         <option value="100">50 qty</option>
				                                        <option value="100">100 qty</option>
				                                    </select>
				                                </div>
				                            </div>
				                            <div class="form-group">
                                                <label for="cc-payment" class="control-label mb-1">Store  Description</label>
                                                <textarea name="description" id="textarea-input" rows="9" placeholder="Content..." class="form-control">No Description Yet</textarea>
                                            </div>
                                            <div>
                                                <button id="payment-button" type="submit" class="btn btn-lg bttn btn-block">
                                                    <i class="fa fa-lock fa-lg"></i>&nbsp;
                                                    <span id="payment-button-amount">Setup</span>
                                                </button>
                                            </div>
                                        </form>
                                    </div>
                                </div>

                            </div>
                        </div> <!-- .card -->

                    </div><!--/.col-->

                    
                    
                    
                    
                 </div>
                 
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="container-fluid">
                                <p></p><br>
                                <p></p><br>
                                <p></p><br>
                                <p></p><br>
                                
                            </div>
                            </div>
                        </div>
                  </div>
                 
{% endblock content %}

store/templates/store/all_store.html
{% extends 'main/base.html' %}
  

{% block content %}
<style type="">
    .card{
    box-shadow: -1px 9px 40px -12px rgba(255,110,110,0.9);
    }
    .card-title{
        font-size: 25px;
        letter-spacing: 1px;
        font-family: Patua One;
        font-weight: 300;
        color: white !important;
        text-shadow: 6px 6px 6px #c9c6c6;
    }
    .card-title1{
        font-size: 25px;
        letter-spacing: 1px;
        font-family: Patua One;
        font-weight: 300;
        color: #357ab7 !important;
        text-shadow: 6px 6px 6px #c9c6c6;
    }

    .bttn{
        background-color: #357ab7;
        color: white;
    }
    .bttn:hover{
        background-color: teal;
        color: white;
        transition:  all 0.5s ease-in-out;
        transform: scale(1.03);
    }
    .card-body{
        background-color: #001f3f;
        color: white;
    }
    .filter{
        font-family: Rufina;

    }

</style>

	<div class="row">
		 <div class="col-md-12">
		      <div class="card">
		  		 <div class="card-body">
		  			 <div id="pay-invoice">
	
		<form action="#" method="post" novalidate="novalidate">
		   	<div class="row form-group">
				 <div class="cols col-lg-4 col-md-4 col-sm-4"><label for="select" class=" form-control-label filter">Select Filter</label></div>
					 <div class="col-12s col-lg-4 col-md-4 col-sm-4">
				           <select name="category" id="select" class="form-control">
				             <option value="0">Please select</option>
				                <option value="1">Option #1</option>
				               <option value="2">Option #2</option>
				               <option value="3">Option #3</option>
				             </select>
				         </div>
				         <div class="col-12s ccol-lg-4 col-md-4 col-sm-4">
				          <button id="payment-button" type="submit" class="btn bttn btns btn-lgs btn-infos btn-blocks">
						     <i class="fa fa-locks fa-lgs"></i>&nbsp;
						         <span id="payment-button-amounts">Go</span>
						      </button>
				         </div>
				    </div>
       </form>
       </div>
      </div>
     </div>
    </div>
       
			 
			 
	</div>



	<div class="row">

                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header">
                                <strong class="card-title1">All Stores</strong>
                            </div>
                            <div class="card-body">
                                <table id="bootstrap-data-table" class="table table-striped table-bordered">
                                    <thead>
                                        <tr>
                                            <th>Name</th>
                                            <th>Products Count</th>
                                            <th>lowest qty</th>
                                            <th>highest qty</th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    	
                                       {% if stores %}
                                        		{% for store in stores %}
                                        			<tr style="background-color: #001f3f; color: white">
                                        				{% if store.products.count <= store.low_qty  %}
                                        					 <td style="background-color: red; color: white;">{{ store.name }}</td>
								                            <td>{{ store.products.count }}</td>
								                            <td>{{ store.low_qty }}</td>
								                            <td>{{ store.high_qty }}</td>
								                            <td>
								                            	<div>
																    <a href="{% url 'store:edit_store' store.id %}" id="payment-button" type="submit" class="btn btn-lg btn-info btn-block">
																       <i class="fa fa-locks fa-lgs"></i>&nbsp;
																       <span id="payment-button-amount">Edit/Delete</span>
																    </a>
															   </div>
								                            </td>
                                        				
                                        				{% else %}
                                        					 <td>{{ store.name }}</td>
								                            <td>{{ store.products.count }}</td>
								                            <td>{{ store.low_qty }}</td>
								                            <td>{{ store.high_qty }}</td>
								                            <td>
								                            	<div>
																    <a href="{% url 'store:edit_store' store.id %}" id="payment-button" type="submit" class="btn btn-lg bttn btn-block">
																       <i class="fa fa-locks fa-lgs"></i>&nbsp;
																       <span id="payment-button-amount">Edit/Delete</span>
																    </a>
															   </div>
								                            </td>
                                        				
                                        				
                                        				{% endif %}
				                                   
				                                    </tr>
				                                  {% endfor %}
				                             
				                             {% else %}    
				                             		<tr>
				                             	<td>Nothing Yet!.</td>
				                                <td>Nothing Yet!.</td>
				                               <td>Nothing Yet!.</td>
				                               <td>Nothing Yet!.</td>
				                               	</tr>
				                            {% endif %}
                                        
                                       
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
	
			</div>
			
			<div class="row">
                    <div class="col-md-12">
                        <div class="card">
                        	<div class="container-fluid">
                 				<p></p><br>
                                <p></p><br>
                                <p></p><br>
                                <p></p><br>
                 				
                 			</div>
                 			</div>
                 		</div>
                  </div>
	

                
{% endblock content %}

store/templates/store/edit_store.html
{% extends 'main/base.html' %}
  

{% block content %}

<style type="">
    .card{
    box-shadow: -1px 9px 40px -12px rgba(255,110,110,0.9);
    }
    .card-title{
        font-size: 25px;
        letter-spacing: 1px;
        font-family: Patua One;
        font-weight: 300;
        color: white !important;
        text-shadow: 6px 6px 6px #c9c6c6;
    }

    .bttn{
        background-color: #357ab7;
    }
    .bttn1{
        background-color: #ED5565;
        color: white;
    }
    .bttn1:hover{
        background-color: #ED5565;
        color: white;
        transition:  all 0.5s ease-in-out;
        transform: scale(1.05);
    }
    .bttn:hover{
        background-color: teal;
        color: white;
        transition:  all 0.5s ease-in-out;
        transform: scale(1.05);
    }
    .card-body{
        background-color: #001f3f;
        color: white;
    }
    .card-title1{
        font-size: 25px;
        letter-spacing: 1px;
        font-family: Patua One;
        font-weight: 300;
        color: #357ab7 !important;
        text-shadow: 6px 6px 6px #c9c6c6;
    }

</style>
	

<div class="row">
                    <div class="col-md-10">
                        <div class="card">
                            <div class="card-header">
                                <strong class="card-title1">Edit Store</strong>
                            </div>
                            <div class="card-body">
                                <!-- Credit Card -->
                                <div id="pay-invoice">
                                    <div class="card-body">
                                        <div class="card-title">
                                            <h3 class="text-center">Update Store</h3>
                                        </div>
                                        <hr>
                                        <form novalidate="novalidate" method="post" enctype="multipart/form-data">
				{% csrf_token %}
                                            
                                            <div class="form-group">
                                                <label for="cc-payment" class="control-label mb-1">Store  Name</label>
                                                <input id="cc-payment" value="{{ store.name }}" name="name" type="text" class="form-control" aria-required="true" aria-invalid="false">
                                            </div>
                                            <div class="form-group">
                                                <label for="cc-payment" class="control-label mb-1">Product Threshold</label>
                                                <input id="cc-payment" value="{{ store.low_qty }}" name="low_qty" type="number" class="form-control" aria-required="true" aria-invalid="false">
                                            </div>
				                            <div class="form-group">
                                                <label for="cc-payment" class="control-label mb-1">Highest Limit</label>
                                                <input id="cc-payment" value="{{ store.high_qty }}" name="high_qty" type="number" class="form-control" aria-required="true" aria-invalid="false">
                                            </div>
				                            <div class="form-group">
                                                <label for="cc-payment" class="control-label mb-1">Store  Description</label>
                                                <textarea name="description" id="textarea-input" rows="9" placeholder="Content..." class="form-control">{{ store.description }}</textarea>
                                            </div>
                                            <div>
                                                <button id="payment-button" type="submit" class="btn btn-lg bttn btn-block">
                                                    <i class="fa fa-locks fa-lgs"></i>&nbsp;
                                                    <span id="payment-button-amount">Update</span>
                                                </button>
                                            </div>
                                        </form>
                                    </div>
                                    <div class="card-body">
                                     <a href="{% url 'store:delete_store' store.id %}" id="payment-button" type="submit" class="btn btn-lg bttn1 btn-block">
										<i class="fa fa-locks fa-lgs"></i>&nbsp;
										 <span id="payment-button-amount">Delete</span>
									 </a>
									</div>
                                </div>

                            </div>
                        </div> <!-- .card -->

                    </div><!--/.col-->

                    
                    
                    
                    
                 </div>
                 
{% endblock content %}