ims/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
	path("", include("main.urls")),
	path("", include("product.urls")),
	path("", include("store.urls")),
	path("", include("customer.urls")),
	path("", include("purchase.urls")),
	path("", include("account.urls")),

]

purchase/urls.py
from django.urls import path
from . import views

app_name = "purchase"

urlpatterns = [

	path("add-purchase/", views.AddPurchaseView, name="add_purchase"),
	path("all-purchase/", views.AllPurchaseView, name="all_purchase"),
	path("delete-purchase/<int:purchase_id>/", views.DeletePurchaseView, name="delete_purchase"),
	path("view-purchase/<int:purchase_id>/", views.ViewPurchaseView, name="view_purchase"),
	

]

purchase/models.py
from django.db import models
from customer.models import Customer
from product.models import Product, SoldProduct
from django.utils import timezone

# Create your models here.
class Purchase(models.Model):
	customer = models.ForeignKey(Customer, on_delete=models.CASCADE, default="")
	products = models.ManyToManyField(SoldProduct, through="PurchaseProductConnector", through_fields=("purchase", "product"),)
	total_price = models.IntegerField(blank=True, null=True)
	total_products = models.IntegerField(blank=True, null=True)
	purchase_id = models.CharField(max_length=150)
	pub_date = models.DateTimeField(default=timezone.now)
	
	
	def __str__(self):
		return self.customer.name
	
	
class PurchaseProductConnector(models.Model):
	purchase = models.ForeignKey(Purchase, on_delete=models.CASCADE, default="")
	product = models.ForeignKey(SoldProduct, on_delete=models.CASCADE, default="")
	pub_date = models.DateTimeField(default=timezone.now)

purchase/views.py
from purchase.models import Purchase, PurchaseProductConnector
from customer.models import Customer
from product.models import Product, SoldProduct
from main.views import ray_randomiser
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy


# Create your views here.
def AddPurchaseView(request):
	if request.method == "POST":
		name = request.POST.get("name")
		email = request.POST.get("email")
		phone = request.POST.get("phone")
		products = request.POST.get("products")
		pub_date = timezone.now()
		
		if (name == ""):
			return HttpResponse("Error with 'name' field, (Please appropriately fill up all fields)")
		elif  (email == ""):
			return HttpResponse("Error with 'email' field, (Please appropriately fill up all fields)")
		elif  (phone == ""):
			return HttpResponse("Error with 'phone' field, (Please appropriately fill up all fields)")
		elif  (products == ""):
			return HttpResponse("Error with 'product' field, (Please appropriately fill up all fields)")
		
		else: 
		
			try:
				for item in products.split(","):
					if get_object_or_404(Product, product_id=item):
						pass
			

				customer = Customer.objects.create(name=name, email=email, phone=phone, pub_date=pub_date)
				customer.save()

				purchase_id = ray_randomiser()
				purchase = Purchase.objects.create(customer=customer,purchase_id=purchase_id, pub_date=pub_date)
				purchase.save()
		
				product_list = [] #the one to work with 
				product_list2 = [] #the one to delete
				total_price = 0
				total_products = 0
		
				products = "%s" % (products)
			
				#products = str(products)
				#products =  products.split(",")
		
				#return HttpResponse((products))
				for item in products.split(","):
				#for item in products:
					product = get_object_or_404(Product, product_id=item)
					sold_product = SoldProduct.objects.create(name=product.name, cost_price=product.cost_price, 
					selling_price=product.selling_price, expiry_date=product.expiry_date, product_id=product.product_id,
					pub_date=product.pub_date)
					total_price += product.selling_price
					total_products += 1
					product_list.append(sold_product)
					product_list2.append(product)
			
					#return HttpResponse(str(product))
					#pc = PurchaseProductConnector(purchase=purchase, product=product, pub_date=pub_date)
					#pc.save()

		
				purchase.total_price = total_price
				purchase.total_products = total_products
				purchase.save()
		
				for product in product_list:
					pc = PurchaseProductConnector(purchase=purchase, product=product, pub_date=pub_date)
					pc.save()
		
				#return HttpResponse(str(product_list))
				for product in product_list2:
					pr = Product.objects.get(id=product.id)
					pr.delete()


				return HttpResponseRedirect(reverse("purchase:all_purchase"))
				
			except:
					return HttpResponse("Error with 'products' field, (Incorrect Product id)")
	else:
		return render(request, 'purchase/add_purchase.html')
		
	
def AllPurchaseView(request):
	purchases = Purchase.objects.order_by("-pub_date")

	context = {"purchases": purchases}
	return render(request, "purchase/all_purchase.html", context)
	
	
	
def DeletePurchaseView(request, purchase_id):
	purchase = Purchase.objects.get(id=purchase_id)
	purchase.delete()
	#post.save()
		
	return HttpResponseRedirect(reverse("purchase:all_purchase"))
	
	
def ViewPurchaseView(request, purchase_id):
	if request.method == "POST":
		pass
	
	else:
		purchase = get_object_or_404(Purchase, id=purchase_id)
		products = purchase.products.all()
		#return HttpResponse(products)
		context = {"purchase": purchase, "products": products}
		return render(request, 'purchase/view_purchase.html', context)
	
	

purchase/templates/purchase/add_purchase.html
{% extends 'main/base.html' %}
  

{% block content %}
<style type="">
    .card{
    box-shadow: -1px 9px 40px -12px rgba(255,90,90,0.9);
    }
    .card-title{
        font-size: 25px;
        letter-spacing: 1px;
        font-family: Patua One;
        font-weight: 300;
        color: white !important;
        text-shadow: 6px 6px 6px #c9c6c6;
    }
    .card-title1{
        font-size: 25px;
        letter-spacing: 1px;
        font-family: Patua One;
        font-weight: 300;
        color: #357ab7 !important;
        text-shadow: 6px 6px 6px #c9c6c6;
    }

    .bttn{
        background-color: #357ab7;
    }
    .bttn:hover{
        background-color: teal;
        color: white;
        transition:  all 0.5s ease-in-out;
        transform: scale(1.05);
    }
    .card-body{
        background-color: #001f3f;
        color: white;
    }
    .filter{
        font-family: Rufina;
    }

</style>	

<div class="row">
                    <div class="col-md-10">
                        <div class="card">
                            <div class="card-header">
                                <strong class="card-title1">Register Purchase</strong>
                            </div>
                            <div class="card-body">
                                <!-- Credit Card -->
                                <div id="pay-invoice">
                                    <div class="card-body">
                                        <div class="card-title">
                                            <h3 class="text-center">Register Purchase</h3>
                                        </div>
                                        <hr>
                                        <form novalidate="novalidate" method="post" enctype="multipart/form-data">
				                        {% csrf_token %}
				
                                        
                                        	<div class="form-group">
                                                <label for="cc-payment" class="control-label mb-1">Add Product(Product id)</label>
                                               <input id="cc-payment" class="form-control" name="products" type="text" data-role="tagsinput" aria-required="true" aria-invalid="false"/>
                                            </div>
                                            
                                            <div class="form-group">
                                                <label for="cc-payment" class="control-label mb-1">Customer Name</label>
                                                <input id="cc-payment" name="name" type="text" class="form-control" aria-required="true" aria-invalid="false">
                                            </div>
                                            <div class="form-group">
                                                <label for="cc-payment" class="control-label mb-1">Customer Email</label>
                                                <input value="noemail@email.com" id="cc-payment" name="email" type="text" class="form-control" aria-required="true" aria-invalid="false">
                                            </div>
                                            <div class="form-group">
                                                <label for="cc-payment" class="control-label mb-1">Customer Phone</label>
                                                <input id="cc-payment" name="phone" type="text" class="form-control" aria-required="true" aria-invalid="false">
                                            </div>

                                            <div class="form-group">                               
                                               
                                               
                                            </div>
                                            
                      
                                            <div>
                                                <button id="payment-button" type="submit" class="btn btn-lg bttn btn-block">
                                                    <i class="fa fa-locks fa-lgs"></i>&nbsp;
                                                    <span id="payment-button-amount">Register</span>
                                                </button>
                                            </div>
                                        </form>
                                    </div>
                                </div>

                            </div>
                        </div> <!-- .card -->

                    </div><!--/.col-->

                    
                    
                    
                    
                 </div>
                 
                 <div class="row">
                    <div class="col-md-10">
                        <div class="card">
                        	<div class="container-fluid">
                 				<p><strong> Instructions:</strong></p>
                 				<p>Include purchase by adding product name or i.d, customers name, customers email address and the customers phone number</p>
                 				
                 			</div>
                 			</div>
                 		</div>
                  </div>
                 
{% endblock content %}

purchase/templates/purchase/all_purchase.html
{% extends 'main/base.html' %}
  

{% block content %}
<style type="">
    .card{
    box-shadow: -1px 9px 40px -12px rgba(255,110,110,0.9);
    }
    .card-title{
        font-size: 25px;
        letter-spacing: 1px;
        font-family: Patua One;
        font-weight: 300;
        color: white !important;
        text-shadow: 6px 6px 6px #c9c6c6;
    }
    .card-title1{
        font-size: 25px;
        letter-spacing: 1px;
        font-family: Patua One;
        font-weight: 300;
        color: #357ab7 !important;
        text-shadow: 6px 6px 6px #c9c6c6;
    }


    .bttn{
        background-color: #357ab7;
        color: white;
    }
    .bttn:hover{
        background-color: teal;
        color: white;
        transition:  all 0.5s ease-in-out;
        transform: scale(1.05);
    }
    .card-body{
        background-color: #001f3f;
        color: white;
    }
    .filter{
        font-family: Rufina;
    }

</style>



	<div class="row">
		 <div class="col-md-12">
		      <div class="card">
		  		 <div class="card-body">
		  			 <div id="pay-invoice">
	
		<form action="#" method="post" novalidate="novalidate">
		   	<div class="row form-group">
				 <div class="cols col-lg-4 col-md-4 col-sm-4"><label for="select" class=" form-control-label filter">Select Filter</label></div>
					 <div class="col-12s col-lg-4 col-md-4 col-sm-4">
				           <select name="category" id="select" class="form-control">
				             <option value="0">Please select</option>
				                <option value="1">Option #1</option>
				               <option value="2">Option #2</option>
				               <option value="3">Option #3</option>
				             </select>
				         </div>
				         <div class="col-12s ccol-lg-4 col-md-4 col-sm-4">
				          <button id="payment-button" type="submit" class="btn bttn btns btn-lgs btn-infos btn-blocks">
						     <i class="fa fa-locks fa-lgs"></i>&nbsp;
						         <span id="payment-button-amounts">Go</span>
						      </button>
				         </div>
				    </div>
       </form>
       </div>
      </div>
     </div>
    </div>
       
			 
			 
	</div>




	<div class="row">

                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header">
                                <strong class="card-title1">All Purchases</strong>
                            </div>
                            <div class="card-body">
                                <table id="bootstrap-data-table" class="table table-striped table-bordered">
                                    <thead>
                                        <tr>
                                            <th>Customer</th>
                                            <th>Price Paid</th>
                                            <th>Purchase id</th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    	
                                        {% if purchases %}
                                        		{% for purchase in purchases %}
                                        			<tr style="background-color: #001f3f; color: white">
				                                    <td>{{ purchase.customer.name }}</td>
				                                    <td>{{ purchase.total_price }}</td>
				                                    <td>{{ purchase.purchase_id }}</td>
				                                    
				                                    <td>
				                                    	<div>
												            <a href="{% url 'purchase:view_purchase' purchase.id %}" id="payment-button" type="submit" class="btn btn-lg bttn btn-block">
												               <i class="fa fa-locks fa-lgs"></i>&nbsp;
												               <span id="payment-button-amount">View</span>
												            </a>
												       </div>
				                                    </td>
				                                    </tr>
				                                  {% endfor %}
				                             
				                             {% else %}    
				                             		<tr>
				                             	<td>Nothing Yet!.</td>
				                                <td>Nothing Yet!.</td>
				                               <td>Nothing Yet!.</td>
				                               <td>Nothing Yet!.</td>
				                               	</tr>
				                            {% endif %}
                                       
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
	
			</div>
	

                
{% endblock content %}

purchase/templates/purchase/view_purchase.html
{% extends 'main/base.html' %}

{% block content %}
<style type="">
    .card{
    box-shadow: -1px 9px 40px -12px rgba(255,110,110,0.9);
    }
    .card-title{
        font-size: 25px;
        letter-spacing: 1px;
        font-family: Patua One;
        font-weight: 300;
        color: white !important;
        text-shadow: 6px 6px 6px #c9c6c6;
    }

    .bttn{
        background-color: #357ab7;
    }
    .bttn1{
        background-color: #ED5565;
        color: white;
    }
    .bttn1:hover{
        background-color: #ED5565;
        color: white;
        transition:  all 0.5s ease-in-out;
        transform: scale(1.02);
    }
    .bttn:hover{
        background-color: teal;
        color: white;
        transition:  all 0.5s ease-in-out;
        transform: scale(1.05);
    }
    .card-body{
        background-color: #001f3f;
        color: white;
    }
    .card-title1{
        font-size: 25px;
        letter-spacing: 1px;
        font-family: Patua One;
        font-weight: 300;
        color: #357ab7 !important;
        text-shadow: 6px 6px 6px #c9c6c6;
    }

</style>
	

<div class="row">
                    <div class="col-md-10">
                        <div class="card">
                            <div class="card-header">
                                <strong class="card-title1">Receipt</strong>
                            </div>
                            <div class="card-body">
                                <!-- Credit Card -->
                                <div id="pay-invoice">
                                    <div class="card-body">
                                        <div class="card-title">
                                            <h3 class="text-center">Receipt</h3>
                                        </div>
                                        <hr>
                                        <p>Customer's name: {{ purchase.customer.name }}</p>
                                        <br />
                                        <p>List of Products:</p>
                                        <hr>
                                        <ul>
		                                    {% for product in products %}
		                                    	<li><p>{{ product.name }} -- {{ product.selling_price }}</p></li>  
		                                    {% endfor %}
                                        </ul>
                                        <br />
                                        <br />
                                        <p>Total Price: {{ purchase.total_price }}</p>
                                        <p>Purchase id: {{ purchase.purchase_id }}</p>
                                    </div>
                                </div>

                            </div>
                            
                             <div class="card-body">
                                     <a href="{% url 'purchase:delete_purchase' purchase.id %}" id="payment-button" type="submit" class="btn btn-lg bttn1 btn-block">
										<i class="fa fa-locks fa-lgs"></i>&nbsp;
										 <span id="payment-button-amount">Delete</span>
									 </a>
									</div>
                        </div> <!-- .card -->

                    </div><!--/.col-->

                    
                    
                    
                    
                 </div>
                 
{% endblock content %}