ims/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
	path("", include("main.urls")),
	path("", include("product.urls")),
	path("", include("store.urls")),
	path("", include("customer.urls")),
	path("", include("purchase.urls")),
	path("", include("account.urls")),

]

product/urls.py
from django.urls import path
from . import views

app_name = "product"

urlpatterns = [

	path("add-product/", views.AddProductView, name="add_product"),
	path("all-product/", views.AllProductView, name="all_product"),
	path("delete-product/<int:product_id>/", views.DeleteProductView, name="delete_product"),
	path("edit-product/<int:product_id>/", views.EditProductView, name="edit_product"),
	

]

product/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Product(models.Model):
	name = models.CharField(max_length=150)
	cost_price = models.IntegerField(blank=False)
	selling_price = models.IntegerField(blank=True, null=True)
	expiry_date = models.CharField(max_length=150)
	product_id = models.CharField(max_length=150)
	pub_date = models.DateTimeField(default=timezone.now)
	
	
	def __str__(self):
		return self.name
		
		
# Create your models here.
class SoldProduct(models.Model):
	name = models.CharField(max_length=150)
	cost_price = models.IntegerField(blank=True, null=True)
	selling_price = models.IntegerField(blank=True, null=True)
	expiry_date = models.CharField(max_length=150)
	product_id = models.CharField(max_length=150)
	pub_date = models.DateTimeField(default=timezone.now)
	
	
	def __str__(self):
		return self.name

product/views.py
from product.models import Product
from store.models import Store, StoreProductConnector
from main.views import ray_randomiser
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy

# Create your views here.
def AddProductView(request):
	if request.method == "POST":
		name = request.POST.get("name")
		cost_price = request.POST.get("cost_price")
		selling_price = request.POST.get("selling_price")
		expiry_date = request.POST.get("expiry_date")
		store_id = request.POST.get("store")
		product_id = ray_randomiser()
		pub_date = timezone.now()
		#return HttpResponse(expiry_date)
		
		if (name == ""):
			return HttpResponse("Error with 'name' field, (Please appropriately fill up all fields)")
		elif  (expiry_date == ""):
			return HttpResponse("Error with 'expiry_date' field, (Please appropriately fill up all fields)")
			
		else: 
			#return HttpResponse(expiry_date) 2020-06-09
		
			product = Product.objects.create(name=name, cost_price=cost_price, selling_price=selling_price, expiry_date=expiry_date, product_id=product_id, pub_date=pub_date)
			product.save()
			
		if store_id == "none":
			pass
			
		else:
			store = get_object_or_404(Store, id=store_id)
			st = StoreProductConnector(store=store, product=product, pub_date=pub_date)
			st.save()
		return HttpResponseRedirect(reverse("product:all_product"))
		
	else:
		stores = Store.objects.order_by("-pub_date")
		context = {"stores": stores}
		return render(request, 'product/add_product.html', context)
		
	
def AllProductView(request):
	#return HttpResponse(timezone.now())
	today_date = str(timezone.now())
	today_date = today_date[0:10]
	products = Product.objects.order_by("-pub_date")

	context = {"products": products, "today_date": today_date}
	return render(request, "product/all_product.html", context)
	
	
	
def DeleteProductView(request, product_id):
	product = Product.objects.get(id=product_id)
	product.delete()
	#post.save()
		
	return HttpResponseRedirect(reverse("product:all_product"))
	
def EditProductView(request, product_id):
	
	if request.method == "POST":
		name = request.POST.get("name")
		cost_price = request.POST.get("cost_price")
		selling_price = request.POST.get("selling_price")
		expiry_date = request.POST.get("expiry_date")
		
		
		
		product = Product.objects.filter(id=product_id)
		product.update(name=name, cost_price=cost_price, selling_price=selling_price, expiry_date=expiry_date)
		#product.save()
		
		return HttpResponseRedirect(reverse("product:all_product"))
		
		
	else:
		product = get_object_or_404(Product, id=product_id)
		context = {"product": product}
		#expiry_date = product.expiry_date
		#return HttpResponse(expiry_date)
		return render(request, 'product/edit_product.html', context)
	
	

product/templates/product/add_product.html
{% extends 'main/base.html' %}
  

{% block content %}
<style type="">
    .card{
    box-shadow: -1px 9px 40px -12px rgba(255,110,110,0.9);
    }
    .card-title{
        font-size: 25px;
        letter-spacing: 1px;
        font-family: Patua One;
        font-weight: 300;
        color: white !important;
        text-shadow: 6px 6px 6px #c9c6c6;
    }

    .bttn{
        background-color: #357ab7;
    }
    .bttn:hover{
        background-color: teal;
        color: white;
        transition:  all 0.5s ease-in-out;
        transform: scale(1.05);
    }
    .card-body{
        background-color: #001f3f;
        color: white;
    }
    .card-title1{
        font-size: 25px;
        letter-spacing: 1px;
        font-family: Patua One;
        font-weight: 300;
        color: #357ab7 !important;
        text-shadow: 6px 6px 6px #c9c6c6;
    }

</style>

<div class="row">
                    <div class="col-md-10">
                        <div class="card">
                            <div class="card-header">
                                <strong class="card-title1">Add Product</strong>
                            </div>
                            <div class="card-body">
                                <!-- Credit Card -->
                                <div id="pay-invoice">
                                    <div class="card-body">
                                        <div class="card-title">
                                            <h3 class="text-center">Add Product</h3>
                                        </div>
                                        <hr>
                                        <form novalidate="novalidate" method="post" enctype="multipart/form-data">
				{% csrf_token %}
                                            
                                            <div class="form-group">
                                                <label for="cc-payment" class="control-label mb-1">Product  Name</label>
                                                <input id="cc-payment" name="name" type="text" class="form-control" aria-required="trues" aria-invalid="falses" required="required">
                                            </div>
                                            <div class="row form-group">
				                                <div class="col col-md-3"><label for="select" class=" form-control-label">Select Store</label></div>
				                                <div class="col-12 col-md-9">
				                                    <select name="store" id="select" class="form-control">
				                                    	{% if stores %}
				                                    		{% for store in stores %}
								                                <option value="{{ store.id }}">{{ store.name }}</option>  
								                             {% endfor %}
								                             
								                          {% else %}
						                                    	<option value="none">No Store</option>
				                                        {% endif %}
				                                    </select>
				                                </div>
				                            </div>
				                           <div class="form-group">
                                                <label for="cc-payment" class="control-label mb-1">Cost Price(₦)</label>
                                                <input value="0" id="cc-payment" name="cost_price" type="number" class="form-control" aria-required="true" aria-invalid="false" required="required">
                                            </div>
                                            
                                            <div class="form-group">
                                                <label for="cc-payment" class="control-label mb-1">Selling Price(₦)</label>
                                                <input value="0" id="cc-payment" name="selling_price" type="number" class="form-control" aria-required="true" aria-invalid="false" required="required">
                                            </div>
                                            
                                           <div class="form-group">
                                                <label for="cc-payment" class="control-label mb-1">Expiration Date</label>
                                                <input id="cc-payment" name="expiry_date" type="date" class="form-control" aria-required="true" aria-invalid="false" required="required">
                                            </div>
                                            
                      
                                            <div>
                                                <button id="payment-button" type="submit" class="btn btn-lg bttn btn-block">
                                                    <i class="fa fa-locks fa-lgs"></i>&nbsp;
                                                    <span id="payment-button-amount">Add</span>
                                                </button>
                                            </div>
                                        </form>
                                    </div>
                                </div>

                            </div>
                        </div> <!-- .card -->

                    </div><!--/.col-->

                    
                    
                    
                    
                 </div>
                 
                  <div class="row">
                    <div class="col-md-10">
                        <div class="card">
                        	<div class="container-fluid">
                 				<p><strong>Instructions:</strong></p>
                 				<p>Add product name, store name to indicate which store the product goes into, the cost of the product and the selling price(this enables profits to be calculated), and expiry date to know when the product expires </p>
                 				
                 			</div>
                 			</div>
                 		</div>
                  </div>
                 
{% endblock content %}

product/templates/product/all_product.html
{% extends 'main/base.html' %}
  

{% block content %}
<style type="">
    .card{
    box-shadow: -1px 9px 40px -12px rgba(255,110,110,0.9);
    }
    .card-title{
        font-size: 25px;
        letter-spacing: 1px;
        font-family: Patua One;
        font-weight: 300;
        color: #357ab7 !important;
        text-shadow: 6px 6px 6px #c9c6c6;
    }
    .card-title1{
        font-size: 25px;
        letter-spacing: 1px;
        font-family: Patua One;
        font-weight: 300;
        color: white !important;
        text-shadow: 6px 6px 6px #c9c6c6;
    }

    .bttn{
        background-color: #357ab7;
        color: black;
    }
    .bttn:hover{
        background-color: teal;
        color: white;
        transition:  all 0.5s ease-in-out;
        transform: scale(1.05);
    }
    .card-body{
        background-color: #001f3f;

    }
    .filter{
    	font-family: Rufina;
    	color: white;
    }
    .table{
    	 background-color: #001f3f;
    }

</style>
	<div class="row">
		 <div class="col-md-12">
		      <div class="card">
		  		 <div class="card-body">
		  			 <div id="pay-invoice">
	
		<form action="#" method="post" novalidate="novalidate">
		   	<div class="row form-group">
				 <div class="cols col-lg-4 col-md-4 col-sm-4"><label for="select" class=" form-control-label filter">Select Filter</label></div>
					 <div class="col-12s col-lg-4 col-md-4 col-sm-4">
				           <select name="category" id="select" class="form-control">
				             <option value="0">Please select</option>
				                <option value="1">Option #1</option>
				               <option value="2">Option #2</option>
				               <option value="3">Option #3</option>
				             </select>
				         </div>
				         <div class="col-12s ccol-lg-4 col-md-4 col-sm-4">
				          <button id="payment-button" type="submit" class="btn bttn btns btn-lgs btn-infos btn-blocks">
						     <i class="fa fa-locks fa-lgs"></i>&nbsp;
						         <span id="payment-button-amounts">Go</span>
						      </button>
				         </div>
				    </div>
       </form>
       </div>
      </div>
     </div>
    </div>
       
			 
			 
	</div>


	<div class="row">

                    <div class="col-md-12">
                        <div class="card" style="background-color: #001f3f;">
                            <div class="card-header">
                                <strong class="card-title1">All Products</strong>
                            </div>
                            <div class="card-body">
                                <table id="bootstrap-data-table" class="table table-striped table-bordered">
                                    <thead>
                                        <tr class="text-white">
                                            <th>Name</th>
                                            <th>Selling Price(₦)</th>
                                            <th>Expiry Date</th>
                                            <th>Product id</th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    	
                                       
                                        	{% if products %}
                                        		{% for product in products %}
                                        			{% if today_date >= product.expiry_date %}
		                                    			<tr style="background-color: #001f3f; color: white">
						                                <td style="background-color: #ED5565; color: white;">{{ product.name }}</td>
						                                <td>{{ product.selling_price }}</td>
						                                <td>{{ product.expiry_date }}</td>
						                                <td>{{ product.product_id }}</td>
						                                <td>
						                                	<div>
														        <a href="{% url 'product:edit_product' product.id %}" id="payment-button" type="submit" class="btn btn-lg bttn btn-block">
														           <i class="fa fa-locks fa-lgs"></i>&nbsp;
														           <span id="payment-button-amount">Edit/Delete</span>
														        </a>
														   </div>
						                                </td>
						                                </tr>
						                               {% else %}
								                           	<tr style="background-color: #001f3f; color: white">
								                            <td>{{ product.name }}</td>
								                            <td>{{ product.selling_price }}</td>
								                            <td>{{ product.expiry_date }}</td>
								                            <td>{{ product.product_id }}</td>
								                            <td>
								                            	<div>
																    <a href="{% url 'product:edit_product' product.id %}" id="payment-button" type="submit" class="btn btn-lg bttn btn-block">
																       <i class="fa fa-locks fa-lgs"></i>&nbsp;
																       <span id="payment-button-amount">Edit/Delete</span>
																    </a>
															   </div>
								                            </td>
								                            </tr>
						                               {% endif %}
				                                  {% endfor %}
				                             
				                             {% else %}    
				                             		<tr>
				                             	<td>Nothing Yet!.</td>
				                                <td>Nothing Yet!.</td>
				                               <td>Nothing Yet!.</td>
				                               <td>Nothing Yet!.</td>
				                               	</tr>
				                            {% endif %}
				                                    
				                                
				                             
                                        
                                        
                                       
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
	
			</div>
			
			<div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="container-fluid">
                                <p></p><br>
                                <p></p><br>
                                <p></p><br>
                                <p></p><br>
                                
                            </div>
                            </div>
                        </div>
                  </div>

                
{% endblock content %}

product/templates/product/edit_product.html
{% extends 'main/base.html' %}
  

{% block content %}
<style type="">
    .card{
    box-shadow: -1px 9px 40px -12px rgba(255,110,110,0.9);
    }
    .card-title{
        font-size: 25px;
        letter-spacing: 1px;
        font-family: Patua One;
        font-weight: 300;
        color: white !important;
        text-shadow: 6px 6px 6px #c9c6c6;
    }

    .bttn{
        background-color: #357ab7;
    }
    .bttn1{
        background-color: #ED5565;
        color: white;
    }
    .bttn1:hover{
        background-color: #ED5565;
        color: white;
        transition:  all 0.5s ease-in-out;
        transform: scale(1.05);
    }
    .bttn:hover{
        background-color: teal;
        color: white;
        transition:  all 0.5s ease-in-out;
        transform: scale(1.05);
    }
    .card-body{
        background-color: #001f3f;
        color: white;
    }
    .card-title1{
        font-size: 25px;
        letter-spacing: 1px;
        font-family: Patua One;
        font-weight: 300;
        color: #357ab7 !important;
        text-shadow: 6px 6px 6px #c9c6c6;
    }

</style>
	

<div class="row">
                    <div class="col-md-10">
                        <div class="card">
                            <div class="card-header">
                                <strong class="card-title1">Edit Product</strong>
                            </div>
                            <div class="card-body">
                                <!-- Credit Card -->
                                <div id="pay-invoice">
                                    <div class="card-body">
                                        <div class="card-title">
                                            <h3 class="text-center">EditProduct</h3>
                                        </div>
                                        <hr>
                                        <form novalidate="novalidate"method="post" enctype="multipart/form-data">
				{% csrf_token %}
                                            
                                            <div class="form-group">
                                                <label for="cc-payment" class="control-label mb-1">Product  Name</label>
                                                <input id="cc-payment" value="{{ product.name }}" name="name" type="text" class="form-control" aria-required="true" aria-invalid="false">
                                            </div>
                                            <div class="row form-group">
				                                <div class="col col-md-3"><label for="select" class=" form-control-label">Select Store</label></div>
				                                <div class="col-12 col-md-9">
				                                    <select name="store" id="select" class="form-control">
				                                    	{% if stores %}
				                                    		{% for store in stores %}
								                                <option value="{{ store }}">{{ store }}</option>  
								                             {% endfor %}
								                             
								                          {% else %}
						                                    	<option value="0">Please select</option>
				                                        {% endif %}
				                                    </select>
				                                </div>
				                            </div>
				                           <div class="form-group">
                                                <label for="cc-payment" class="control-label mb-1">Cost Price(₦)</label>
                                                <input id="cc-payment" value="{{ product.cost_price }}" name="cost_price" type="number" class="form-control" aria-required="true" aria-invalid="false">
                                            </div>
                                            
                                            <div class="form-group">
                                                <label for="cc-payment" class="control-label mb-1">Selling Price(₦)</label>
                                                <input id="cc-payment" value="{{ product.selling_price }}" name="selling_price" type="number" class="form-control" aria-required="true" aria-invalid="false">
                                            </div>
                                            
                                           <div class="form-group">
                                                <label for="cc-payment" class="control-label mb-1">Expiration Date</label>
                                                <input id="cc-payment" value="{{ product.expiry_date }}" name="expiry_date" type="date" class="form-control" aria-required="true" aria-invalid="false">
                                            </div>
                                            
                      
                                            <div>
                                                <button id="payment-button" type="submit" class="btn btn-lg bttn btn-block">
                                                    <i class="fa fa-locks fa-lgs"></i>&nbsp;
                                                    <span id="payment-button-amount">Update</span>
                                                </button>
                                            </div>
                                        </form>
                                    </div>
                                    <div class="card-body">
                                     <a href="{% url 'product:delete_product' product.id %}" id="payment-button" type="submit" class="btn btn-lg bttn1 btn-block">
										<i class="fa fa-locks fa-lgs"></i>&nbsp;
										 <span id="payment-button-amount">Delete</span>
									 </a>
									</div>
                                </div>

                            </div>
                        </div> <!-- .card -->

                    </div><!--/.col-->

                    
                    
                    
                    
                 </div>
                 
{% endblock content %}