account/urls.py
from django.urls import path
from . import views

app_name = "account"

urlpatterns = [

	path("account/", views.AccountView, name="account"),
	

]

customer/urls.py
from django.urls import path
from . import views

app_name = "customer"

urlpatterns = [

	path("add-customer/", views.AddCustomerView, name="add_customer"),
	path("all-customer/", views.AllCustomerView, name="all_customer"),
	path("delete-customer/", views.DeleteCustomerView, name="delete_customer"),
	path("edit-customer/", views.EditCustomerView, name="edit_customer"),
	

]

ims/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
	path("", include("main.urls")),
	path("", include("product.urls")),
	path("", include("store.urls")),
	path("", include("customer.urls")),
	path("", include("purchase.urls")),
	path("", include("account.urls")),

]

main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [

	path("", views.IndexView, name="index"),
	path("about/", views.AboutView, name="about"),

]

product/urls.py
from django.urls import path
from . import views

app_name = "product"

urlpatterns = [

	path("add-product/", views.AddProductView, name="add_product"),
	path("all-product/", views.AllProductView, name="all_product"),
	path("delete-product/<int:product_id>/", views.DeleteProductView, name="delete_product"),
	path("edit-product/<int:product_id>/", views.EditProductView, name="edit_product"),
	

]

store/urls.py
from django.urls import path
from . import views

app_name = "store"

urlpatterns = [

	path("add-store/", views.AddStoreView, name="add_store"),
	path("all-store/", views.AllStoreView, name="all_store"),
	path("delete-store/<int:store_id>/", views.DeleteStoreView, name="delete_store"),
	path("edit-store/<int:store_id>/", views.EditStoreView, name="edit_store"),
	

]

main/models.py
from django.db import models

# Create your models here.

main/views.py
import random
import string
from django.shortcuts import render
from customer.models import Customer
from product.models import Product
from purchase.models import Purchase
from store.models import Store
#more models import

# Create your views here.
def IndexView(request):
	customers = Customer.objects.all()
	products = Product.objects.all()
	stores = Store.objects.all()
	purchases = Purchase.objects.all()
	

	context = {"customers": customers, "products": products, "stores": stores, "purchases": purchases}
	return render(request, "main/index.html", context)
	
	
def AboutView(request):
	return render(request, "main/about.html")
	
	
def ray_randomizer(lettersCount, digitsCount):
	sampleStr = ' '.join((random.choice(string.ascii_letters) for i in range(lettersCount)))
	sampleStr += ' '.join((random.choice(string.digits) for i in range(digitsCount)))
	
	sampleList = list(sampleStr)
	random.shuffle(sampleList)
	result = ' '.join(sampleList)
	return result
	
	
def ray_randomiser(length=6):
	landd = string.ascii_letters + string.digits
	return ''.join((random.choice(landd) for i in range(length)))
	
	

main/templates/main/about.html
{% extends 'main/base.html' %}
  

{% block content %}
<style type="">
    .card{
    box-shadow: -1px 9px 40px -12px rgba(255,110,110,0.9);
    }
    .card-title{
        font-size: 25px;
        letter-spacing: 1px;
        font-family: Patua One;
        font-weight: 300;
        color: #fff !important;
        text-shadow: 6px 6px 6px #c9c6c6;
    }
    .card-title1{
        font-size: 25px;
        letter-spacing: 1px;
        font-family: Patua One;
        font-weight: 300;
        color: #357ab7 !important;
        text-shadow: 6px 6px 6px #c9c6c6;
    }


    .bttn{
        background-color: #357ab7;
    }
    .bttn:hover{
        background-color: teal;
        color: white;
        transition:  all 0.5s ease-in-out;
        transform: scale(1.05);
    }
    .card-body{
        background-color: #001f3f;
        color: #001f3f;
    }
    .card-body i{
        color: #001f3f;
    }
    .text{
       background-color: #001f3f;
       color: #fff;
        font-family: Rufina;
        font-size: 18px;
    }

    .filter{
        font-family: Rufina;
    }
    </style>
<div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header">
                                <strong class="card-title1">About</strong>
                            </div>
                            <div class="card-body">
                                <!-- Credit Card -->
                                <div id="pay-invoice">
                                    <div class="card-body">
                                        <div class="card-title">
                                            <h3 class="text-center">Inventory management System</h3>
                                        </div>
                                        <hr>
                                        <p class="text text-center">
                                        product “RedRock Inventory Management System is a cloud based software which provide a suite of tools to help businesses control their inventory processes. It is used for adding products/inventory to a store, tracking inventory levels, orders, sales, financial reports and deliveries. Join over 2000 businesses using RedRock IMS and avoid product overstock and outages, and organize inventory data.
                                       </p>
                                    </div>
                                </div>

                            </div>
                        </div> <!-- .card -->

                    </div><!--/.col-->
                    
                    
             </div>
{% endblock content %}

main/templates/main/base.html
<!doctype html>
<html class="no-js" lang="">
{% load static %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Tradesray</title>
    <meta name="description" content="Ela Admin - HTML5 Admin Template">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" href="https://i.imgur.com/QRAUqs9.png">
    <link rel="shortcut icon" href="https://i.imgur.com/QRAUqs9.png">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/normalize.css@8.0.0/normalize.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/lykmapipo/themify-icons@0.1.2/css/themify-icons.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pixeden-stroke-7-icon@1.2.3/pe-icon-7-stroke/dist/pe-icon-7-stroke.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.2.0/css/flag-icon.min.css">
    <link rel="stylesheet" href="{% static 'main/assets/css/cs-skin-elastic.css' %}"> 
    <link rel="stylesheet" href="{% static 'main/assets/css/style.css' %}">
    
    <link rel="stylesheet" href="{% static 'main/assets/css/cs-skin-elastic.css' %}">
    <link rel="stylesheet" href="{% static 'main/assets/css/lib/datatable/dataTables.bootstrap.min.css' %}">
    <!-- <script type="text/javascript" src="https://cdn.jsdelivr.net/html5shiv/3.7.3/html5shiv.min.js"></script> -->
    <link href="https://cdn.jsdelivr.net/npm/chartist@0.11.0/dist/chartist.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/jqvmap@1.5.1/dist/jqvmap.min.css" rel="stylesheet">

    <link href="https://cdn.jsdelivr.net/npm/weathericons@2.1.0/css/weather-icons.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/fullcalendar@3.9.0/dist/fullcalendar.min.css" rel="stylesheet" />
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/rainbow/1.2.0/themes/github.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'main/assets/css/bootstrap-tagsinput.css' %}">
    <link rel="stylesheet" href="{% static 'main/assets/css/app.css' %">

</head>
<body>
    <style type="text/css">
.copy {
  font-family: Rufina;
  color: #c89666;
  padding-left: 5px;
  padding-right: 5px;
  padding-bottom: 10px;
  text-align: center;
  width: 100%;
  display: block;
  font-weight: bolder;
  font-size: 20px;
}
.site-footer{
    background: #001f3f;
}
.actives a{
    font-family: Patua One;
    color: white !important;
    text-transform: uppercase;
}

.actives a:hover{
    color: #ED5565 !important;
    transition:  all 0.5s ease-in-out;
    transform: scale(1.05);
}
.actives i{
    color: #fff !important;
    font-size: 18px;
}

.actives i:hover{
    color:#ED5565 !important;
    transition:  all 0.5s ease-in-out;
    transform: scale(1.05);
}

.navbar-nav{
    height: 100%;
    width: 100%;
    background:  #001f3f;
    position: relative;
</style>
<!-- Left Panel -->
    <aside id="left-panel" class="left-panel">
        <nav class="navbar navbar-expand-sm navbar-default">
            <div id="main-menu" class="main-menu collapse navbar-collapse">
                <ul class="nav navbar-nav">

                    <li class="actives">
                        <a href="{% url 'main:index' %}"><i class="menu-icon fa fa-home"></i>Main </a>
                        <hr>
                    </li>
                    <li class="actives">
                        <a href="{% url 'product:add_product' %}"><i class="menu-icon fa fa-cart-plus"></i>Add Product</a>
                    </li>
                    <li class="actives">
                        <a href="{% url 'store:add_store' %}"><i class="menu-icon fa fa-laptop"></i>Setup Store</a>
                    </li>
                    <li class="actives">
                        <a href="{% url 'purchase:add_purchase' %}"><i class="menu-icon fas fa-money-check"></i>Register Purchase</a>
                        <hr>
                    </li>
                    <li class="actives">
                        <a href="{% url 'store:all_store' %}"><i class="menu-icon fa fa-laptop"></i>View Stores</a>
                    </li>
                     <li class="actives">
                        <a href="{% url 'purchase:all_purchase' %}"><i class="menu-icon fas fa-money-bill-alt"></i>Review Purchases</a>
                    </li>
                    <li class="actives">
                        <a href="{% url 'customer:all_customer' %}"><i class="menu-icon fas fa-users"></i>See Customers</a>
                    </li>
                    <li class="actives">
                        <a href="{% url 'product:all_product' %}"><i class="menu-icon fa fa-laptop"></i>Your Products</a>
                         <hr>
                    </li>
                    <li class="actives">
                        <a href="{% url 'account:account' %}"><i class="menu-icon fas fa-file-invoice"></i>Account(₦)</a>
                        <hr>
                    </li>
                    <li class="actives">
                        <a href="{% url 'main:about' %}"><i class="menu-icon fas fa-address-card"></i>About</a>
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </nav>
    </aside>
    <!-- /#left-panel -->
    <div id="right-panel" class="right-panel">
        <!-- Header-->
        <header id="header" class="header">
            <div class="top-left">
                <div class="navbar-header">
                    <a class="navbar-brand" href="./"><img src="{% static 'main/images/logo.png' %}" alt="Logo"></a>
                    <a class="navbar-brand hidden" href="./"><img src="{% static 'main/images/logo2.png' %}" alt="Logo"></a>  
                    <a id="menuToggle" class="menutoggle"><i class="fa fa-bars"></i></a>
                </div>
            </div>
            
        </header>
        <!-- /#header -->
        <div class="content">
            <!-- Animated -->
            <div class="animated fadeIn">


			{% block content %}
			
        	{% endblock content %}
        
        	</div>
       </div>
       
        <div class="clearfix"></div>
        <!-- Footer -->
        <footer class="site-footer" >
            <div class="footer-inner">
                <div class="row">
                    <div class="copy col-lg-12 col-md-8 col-sm-4">
                        Copyright &copy; 2020 Designed by <a href="#" style="color: #c69963">RedRock Technologies ltd</a>
                    </div>
                    
                </div>
            </div>
        </footer>
        <br />
        <!-- /.site-footer -->  
     </div>




    <!-- Scripts -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@2.2.4/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.4/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-match-height@0.7.2/dist/jquery.matchHeight.min.js"></script>
    <script src="{% static 'main/assets/js/main.js' %}"></script>  

    <!--  Chart js -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.7.3/dist/Chart.bundle.min.js"></script>

    <!--Chartist Chart-->
    <script src="https://cdn.jsdelivr.net/npm/chartist@0.11.0/dist/chartist.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartist-plugin-legend@0.6.2/chartist-plugin-legend.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/jquery.flot@0.8.3/jquery.flot.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/flot-pie@1.0.0/src/jquery.flot.pie.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/flot-spline@0.0.1/js/jquery.flot.spline.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/simpleweather@3.1.0/jquery.simpleWeather.min.js"></script>
    <script src="{% static 'main/assets/js/init/weather-init.js' %}"></script> 

    <script src="https://cdn.jsdelivr.net/npm/moment@2.22.2/moment.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/fullcalendar@3.9.0/dist/fullcalendar.min.js"></script>
    <script src="https://kit.fontawesome.com/5bc9974d75.js" crossorigin="anonymous"></script>
    <script src="{% static 'main/assets/js/init/fullcalendar-init.js' %}"></script>
        <script src="{% static 'main/assets/js/lib/data-table/datatables.min.js' %}"></script>
    <script src="{% static 'main/assets/js/lib/data-table/dataTables.bootstrap.min.js' %}"></script>
    <script type="text/javascript">
        $(document).ready(function() {
          $('#bootstrap-data-table-export').DataTable();
      } );
  </script>
  
  
  
  
  	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/typeahead.js/0.11.1/typeahead.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.2.20/angular.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/rainbow/1.2.0/js/rainbow.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/rainbow/1.2.0/js/language/generic.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/rainbow/1.2.0/js/language/html.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/rainbow/1.2.0/js/language/javascript.js"></script>
    <script src="{% static 'main/assets/js/bootstrap-tagsinput.min.js' %}"></script>
    <script src="{% static 'main/assets/js/bootstrap-tagsinput-angular.min.js' %}"></script>
    <script src="{% static 'https://unpkg.com/aos@2.3.1/dist/aos.js' %}"></script>
    <script src="{% static 'main/assets/js/app.js' %}"></script>
    <script src="{% static 'main/assets/js/app_bs3.js' %}"></script>
  
  
  

</body>
</html>

main/templates/main/index.html
{% extends 'main/base.html' %}

  

{% block content %}
<style type="">
    .card{
    box-shadow: -1px 9px 40px -12px rgba(255,110,110,0.9);
    }
    .card-title{
        font-size: 25px;
        letter-spacing: 1px;
        font-family: Patua One;
        font-weight: 300;
        color: #001f3f !important;
        text-shadow: 6px 6px 6px #c9c6c6;
    }
    .card-title1{
        font-size: 25px;
        letter-spacing: 1px;
        font-family: Patua One;
        font-weight: 300;
        color: #357ab7 !important;
        text-shadow: 6px 6px 6px #c9c6c6;
    }
    .teko{
        font-family: Teko;
        color: #001f3f;
    }

    .bttn{
        background-color: #357ab7;
    }
    .bttn:hover{
        background-color: teal;
        color: white;
        transition:  all 0.5s ease-in-out;
        transform: scale(1.05);
    }
    .card-body{
        color: #001f3f;
    }
    .card:hover{
        transform: scale(1.03) !important;
        transition:  all 0.5s ease-in-out;
    }
    .card-body i{
        
        color: #001f3f;
    }
    .filter{
        font-family: Rufina;
    }
    </style>	
	 <!-- /Widgets -->
                <div class="row">
                    <div class="col-sm-6 col-lg-3">
                        <div class="card text-white bg-flat-color-1">
                            <div class="card-body">
                                <div class="card-left pt-1 float-left">
                                    <h3 class="mb-0 fw-r">
                                        <span class="currency float-left mr-1"></span>
                                        <span class="count">{{ products.count }}</span>
                                    </h3>
                                    <p class="text-light mt-1 m-0">Product(s)</p>
                                </div><!-- /.card-left -->

                                <div class="card-right float-right text-right">
                                    <i class="icon fade-5 icon-lg pe-7s-cart"></i>
                                </div><!-- /.card-right -->
                                

                            </div>

                        </div>
                    </div>
                    <!--/.col--> 

                    <div class="col-sm-6 col-lg-3">
                        <div class="card text-white bg-flat-color-6">
                            <div class="card-body">
                                <div class="card-left pt-1 float-left">
                                    <h3 class="mb-0 fw-r">
                                        <span class="count float-left">{{ stores.count }}</span>
                                        <span>.</span>
                                    </h3>
                                    <p class="text-light mt-1 m-0">Store(s)</p>
                                </div><!-- /.card-left -->

                                <div class="card-right float-right text-right">
                                    <div id="flotBar1" class="flotBar1"></div>
                                </div><!-- /.card-right -->

                            </div>

                        </div>
                    </div>
                    <!--/.col-->

                    <div class="col-sm-6 col-lg-3">
                        <div class="card text-white bg-flat-color-3">
                            <div class="card-body">
                                <div class="card-left pt-1 float-left">
                                    <h3 class="mb-0 fw-r">
                                        <span class="count">{{ customers.count }}</span>
                                    </h3>
                                    <p class="text-light mt-1 m-0">Customer(s)</p>
                                </div><!-- /.card-left -->

                                <div class="card-right float-right text-right">
                                    <i class="icon fade-5 icon-lg pe-7s-users"></i>
                                </div><!-- /.card-right -->

                            </div>

                        </div>
                    </div>
                    <!--/.col-->

                    <div class="col-sm-6 col-lg-3">
                        <div class="card text-white bg-flat-color-2">
                            <div class="card-body">
                                <div class="card-left pt-1 float-left">
                                    <h3 class="mb-0 fw-r">
                                        <span class="count">{{ purchases.count }}</span>
                                    </h3>
                                    <p class="text-light mt-1 m-0">Purchase(s)</p>
                                </div><!-- /.card-left -->

                                <div class="card-right float-right text-right">
                                    <div id="flotLine1" class="flotLine1"></div>
                                </div><!-- /.card-right -->

                            </div>

                        </div>
                    </div>
                    <!--/.col-->
                </div>
                <!-- /Widgets -->
                
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                        	<div class="container-fluid">
                 				<p>Notice:</p>
                 				<p><strong>Products:</strong>Indicates the total products in the store </p>
                 				<p><strong>Store:</strong>Shows the total number of store setups made</p>
                 				<p><strong>Customers:</strong>Shows the total number of customers </p>
                 				<p><strong>Prochases:</strong>Shows all purchases made</p>
                 				
                 			</div>
                 			</div>
                 		</div>
                  </div>
                
                
{% endblock content %}